"""LLM-driven relation prototype scorer for hop-aware passage ranking.

This module replaces the static relation-keyword tables (formerly in
``src.graph.entity_scoring`` and ``src.graph.retrieval_query_builder``) with a
dynamic, LLM-generated *relation prototype* for each active hop.

Why?
----
The previous approach scored passage relevance to a hop using a hand-curated
``{relation_label: keywords}`` dictionary -- e.g. ``"born_in" ->
("born", "birthplace", "native", ...)``. That design has two structural
problems:

1. It cannot adapt to new relations or to nuances introduced by *prior hops*.
   A "born_in" hop where the prior hop established a *founder* should be
   scored differently from a "born_in" hop where the prior hop established a
   *composer*: the surrounding cues differ (entrepreneur biographies vs
   musician biographies).

2. The keyword table is not universal. It only covers the relation labels we
   thought of in advance. A new pipeline running over a domain we did not
   anticipate (medical, legal, ecological, ...) gets *zero* relation signal.

The relation-prototype design solves both problems generically:

- One LLM call per (hop, prior-hop chain) tuple produces, with prior-hop
  context, a short structured prototype: a one-sentence description of an
  ideal answer-bearing passage, a list of cue phrases likely to appear in
  such a passage, and an "answer pattern" describing the answer's surface
  form. The LLM is the only knowledge source -- no static tables.

- Per-passage scoring uses the dynamic cues (substring/regex match) so it
  remains cheap. The signal is fully contextualised because the cues come
  from the LLM and are conditioned on the active subject, relation, and the
  full hop history.

The LLM call is cached on the pipeline state per hop_index, so retries
of the same hop reuse the prototype rather than regenerating it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from src.agents.hop_safety import HopRecord
from src.utils.llm import LLMClient


# Maximum cue phrases stored on the prototype. Larger lists slow down per-
# passage scoring and add noise; smaller lists give a noisier signal. Empirical
# sweet spot for current LLM prototypes: 6-10 cues.
_MAX_CUES = 10
_MAX_NEG_CUES = 6
_PROMPT_PREVIEW_CHARS = 120


@dataclass(slots=True)
class RelationPrototype:
    """Structured relation cue bundle generated by the LLM for one hop.

    The prototype is consumed by:
    - the retriever's relation-consistency scoring (cue overlap with passage),
    - the retriever query builder (cues are added as additional query variants),
    - the reasoner's focus-sentence extractor (cues are passed as anchors so
      answer-bearing sentences are surfaced even when a passage is truncated).

    Fields:
    - ``description``: 1-sentence English description of an ideal answer-bearing
      passage for this hop given prior-hop context.
    - ``cue_phrases``: lowercase, short noun phrases / verbs / phrases that an
      answer-bearing passage is likely to contain.
    - ``negative_cue_phrases``: cue phrases whose presence indicates the passage
      describes a DIFFERENT relation about the same subject (so the passage may
      be lexically similar but is the wrong topic).
    - ``answer_pattern``: short string describing the expected answer surface
      form (e.g. ``"city name"``, ``"4-digit year"``, ``"university name"``).
    - ``focus_query``: a single concise query string usable as an additional
      retrieval variant (it bundles the active subject + key relation cues).
    """

    description: str = ""
    cue_phrases: list[str] = field(default_factory=list)
    negative_cue_phrases: list[str] = field(default_factory=list)
    answer_pattern: str = ""
    focus_query: str = ""


def _truncate(text: str, n: int = _PROMPT_PREVIEW_CHARS) -> str:
    t = (text or "").strip()
    return t if len(t) <= n else (t[: max(0, n - 1)] + "\u2026")


def _clean_cue_list(values: Any, max_items: int) -> list[str]:
    """Coerce an arbitrary JSON value into a clean list of short cue strings."""
    if not isinstance(values, (list, tuple)):
        return []
    cleaned: list[str] = []
    seen: set[str] = set()
    for v in values:
        s = str(v or "").strip().strip("\"'.,;:()[]")
        if not s:
            continue
        # Strip leading-articles for stable substring matching.
        s_low = re.sub(r"^(the|an|a)\s+", "", s.lower())
        if not s_low or len(s_low) < 2 or len(s_low) > 50:
            continue
        if s_low in seen:
            continue
        seen.add(s_low)
        cleaned.append(s_low)
        if len(cleaned) >= max_items:
            break
    return cleaned


def _build_prototype_prompt(
    hop: HopRecord,
    prior_hops: list[HopRecord],
    original_question: str,
    resolved_subquestion: str,
    expected_type: str,
    expected_granularity: str,
) -> str:
    """Construct the LLM prompt for prototype generation.

    The prompt includes the full prior-hop chain so the LLM can specialise its
    cues to the current hop *given* the prior subjects/answers. This is what
    makes the scorer "know the steps from previous hops".
    """
    chain_lines: list[str] = []
    for ph in prior_hops:
        chain_lines.append(
            f"  hop{ph.hop_index}: subject={ph.main_entity.text!r} "
            f"({ph.main_entity.entity_type}) --{ph.relation}--> "
            f"answer={ph.answer or '[unresolved]'!r}"
        )
    chain_text = "\n".join(chain_lines) if chain_lines else "  (none -- this is hop 1)"
    granularity_line = (
        f"Required answer granularity: {expected_granularity}\n"
        if expected_granularity
        else ""
    )
    return (
        "You are a retrieval-relevance signal generator. Your job is to describe, "
        "in structured JSON, what an answer-bearing passage looks like for the "
        "ACTIVE HOP given the full prior-hop chain.\n\n"
        "Your output replaces a static relation-keyword table; the cues you list "
        "will be substring-matched against passages, so prefer SHORT, COMMON "
        "phrases that frequently appear in answer-bearing prose.\n\n"
        "Active sub-question: " + (resolved_subquestion or hop.subquestion_text) + "\n"
        f"Active subject: {hop.main_entity.text} ({hop.main_entity.entity_type}, "
        f"role={hop.main_entity.role})\n"
        f"Active relation: {hop.relation}\n"
        f"Expected answer type: {expected_type}\n"
        f"{granularity_line}"
        f"Original multi-hop question: {original_question}\n"
        f"Prior hop chain:\n{chain_text}\n\n"
        "Return STRICT JSON only, no prose, with these keys:\n"
        '{"description": "<one-sentence English description of an ideal '
        'answer-bearing passage for the active sub-question>",\n'
        ' "cue_phrases": ["<6-10 short LOWERCASE cues likely to appear in an '
        'answer-bearing passage; use common verbs, nouns and short phrases such '
        'as \\"founded\\", \\"co-founded\\", \\"founder of\\", not full '
        'sentences>"],\n'
        ' "negative_cue_phrases": ["<up to 6 short LOWERCASE phrases that '
        'indicate the passage discusses a DIFFERENT relation about the same '
        'subject; e.g. for a born_in hop, a phrase like \\"died in\\" would be '
        'a negative cue>"],\n'
        ' "answer_pattern": "<very short description of the answer surface '
        'form, e.g. \\"city name\\", \\"4-digit year\\", \\"university name\\">",\n'
        ' "focus_query": "<a single 6-12-word search query bundling the '
        'active subject and the most diagnostic cue, e.g. \\"<subject> '
        'birthplace city\\">"\n'
        "}\n"
        "Rules:\n"
        "- Cues must be lowercase substrings that commonly appear verbatim in "
        "the kind of passage that would answer the active sub-question.\n"
        "- Do NOT include the subject name in cue_phrases (it is matched "
        "separately via entity overlap).\n"
        "- Do NOT include any benchmark- or dataset-specific tokens.\n"
        "- Tailor cues to the active relation AND to the prior-hop chain: a "
        "born_in hop following a 'founder of' hop should still emphasise "
        "biographical-birth cues, but pick cues that are most likely to appear "
        "in a tech-founder biography (entrepreneurship register).\n"
    )


def generate_relation_prototype(
    llm: LLMClient | None,
    hop: HopRecord,
    prior_hops: list[HopRecord],
    original_question: str,
    resolved_subquestion: str = "",
    expected_type: str = "",
    expected_granularity: str = "",
) -> RelationPrototype:
    """Run one LLM call to generate a relation prototype for the active hop.

    Returns a ``RelationPrototype`` with cleaned cue phrases. On any failure
    (LLM unavailable, malformed JSON, empty response) returns an EMPTY
    prototype rather than raising, so callers can transparently fall back to
    legacy keyword scoring without crashing the pipeline.

    Pipeline contract:
    - Caller invokes this once per (hop_index) and caches the result on the
      pipeline state. Retries of the same hop must reuse the cached prototype
      rather than re-querying the LLM.
    - The prototype is consumed by ``src.graph.entity_scoring`` for passage
      ranking and by ``src.agents.react_reasoner`` for focus-sentence
      extraction. Both consumers tolerate empty cue lists gracefully.
    """
    if llm is None or not hop:
        return RelationPrototype()
    try:
        prompt = _build_prototype_prompt(
            hop=hop,
            prior_hops=prior_hops,
            original_question=original_question,
            resolved_subquestion=resolved_subquestion,
            expected_type=expected_type,
            expected_granularity=expected_granularity,
        )
        response = llm.generate(prompt, max_new_tokens=320)
        parsed = llm.extract_json(response.text)
        if not isinstance(parsed, dict):
            return RelationPrototype()
        return RelationPrototype(
            description=str(parsed.get("description") or "").strip()[:300],
            cue_phrases=_clean_cue_list(parsed.get("cue_phrases"), _MAX_CUES),
            negative_cue_phrases=_clean_cue_list(
                parsed.get("negative_cue_phrases"), _MAX_NEG_CUES
            ),
            answer_pattern=str(parsed.get("answer_pattern") or "").strip()[:80],
            focus_query=str(parsed.get("focus_query") or "").strip()[:160],
        )
    except Exception:
        # Pipeline robustness: scoring must work even when the LLM call fails.
        return RelationPrototype()


def prototype_to_dict(proto: RelationPrototype | None) -> dict[str, Any]:
    """Serialise a ``RelationPrototype`` for embedding in pipeline state."""
    if proto is None:
        return {}
    return {
        "description": proto.description,
        "cue_phrases": list(proto.cue_phrases),
        "negative_cue_phrases": list(proto.negative_cue_phrases),
        "answer_pattern": proto.answer_pattern,
        "focus_query": proto.focus_query,
    }


def prototype_from_dict(payload: Any) -> RelationPrototype:
    """Reconstruct a ``RelationPrototype`` from serialised state."""
    if not isinstance(payload, dict):
        return RelationPrototype()
    return RelationPrototype(
        description=str(payload.get("description") or ""),
        cue_phrases=list(payload.get("cue_phrases") or []),
        negative_cue_phrases=list(payload.get("negative_cue_phrases") or []),
        answer_pattern=str(payload.get("answer_pattern") or ""),
        focus_query=str(payload.get("focus_query") or ""),
    )


def relation_prototype_score(
    passage_text: str,
    prototype: RelationPrototype,
) -> float:
    """Compute a 0..1 relevance score using the prototype's cue phrases.

    The score is purely substring-based against the lowercased passage:
    - +1 unit per cue_phrase substring hit (bounded).
    - -0.5 unit per negative_cue_phrase hit (bounded).
    - Final score is rescaled into [0, 1] using the cue inventory size, so
      passages with many cue hits trend high and passages with none trend low.

    The function returns ``0.5`` (neutral) when the prototype has no cues -- so
    callers can transparently fall back to legacy keyword scoring without
    forcing a particular default. Returns ``0.0`` on empty passage_text.
    """
    if not passage_text:
        return 0.0
    cues = prototype.cue_phrases or []
    neg_cues = prototype.negative_cue_phrases or []
    if not cues:
        return 0.5

    text_low = passage_text.lower()
    pos_hits = sum(1 for c in cues if c and c in text_low)
    neg_hits = sum(1 for c in neg_cues if c and c in text_low)

    # Reward more cue hits but with diminishing returns, so a small handful of
    # high-quality cues already score the passage strongly.
    reward = pos_hits / max(1, len(cues))
    penalty = 0.5 * (neg_hits / max(1, len(neg_cues))) if neg_cues else 0.0
    raw = reward - penalty
    return max(0.0, min(1.0, raw))


def relation_prototype_summary(prototype: RelationPrototype) -> str:
    """Return a short human-readable summary for debug logging."""
    if not prototype:
        return "<empty prototype>"
    desc = _truncate(prototype.description, 80)
    cues = ", ".join(prototype.cue_phrases[:5])
    return f"desc={desc!r}; cues=[{cues}]; pattern={prototype.answer_pattern!r}"


__all__ = [
    "RelationPrototype",
    "generate_relation_prototype",
    "prototype_to_dict",
    "prototype_from_dict",
    "relation_prototype_score",
    "relation_prototype_summary",
]
